/**
 * src/wasm/index.ts
 *
 * Async wrapper around the Emscripten pixelops WASM module.
 *
 * SETUP REQUIRED — before this module works you must compile the WASM:
 *   npm run build:wasm
 * This generates src/wasm/generated/pixelops.js and pixelops.wasm.
 *
 * Usage:
 *   import { getPixelOps, floodFill } from '@/wasm'
 *   const wasmReady = getPixelOps() // call once; subsequent calls return cache
 */

import type {
  PixelOpsModule,
  PixelOpsFactory,
  CurvesHistogramResult,
} from "./types";

// ─── Module singleton ─────────────────────────────────────────────────────────

let _module: PixelOpsModule | null = null;
let _initPromise: Promise<PixelOpsModule> | null = null;

/** Initialise and return the WASM module (idempotent, cached after first call). */
export async function getPixelOps(): Promise<PixelOpsModule> {
  if (_module) return _module;
  if (_initPromise) return _initPromise;

  _initPromise = (async () => {
    // Dynamic import so Vite only bundles these when getPixelOps() is called.
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — file is generated by `npm run build:wasm`
    const { default: factory } = (await import("./generated/pixelops.js")) as {
      default: PixelOpsFactory;
    };
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — generated asset URL resolved by Vite
    const wasmUrl = (await import("./generated/pixelops.wasm?url"))
      .default as string;

    _module = await factory({ locateFile: () => wasmUrl });
    return _module;
  })();

  return _initPromise;
}

// ─── Memory helpers ───────────────────────────────────────────────────────────

/**
 * Copies `data` into WASM memory, calls `fn(ptr)` which may modify it in-place,
 * then copies the (possibly modified) bytes back out and frees the WASM allocation.
 */
function withInPlaceBuffer(
  m: PixelOpsModule,
  data: Uint8Array,
  fn: (ptr: number) => void,
): Uint8Array {
  const ptr = m._malloc(data.byteLength);
  try {
    m.HEAPU8.set(data, ptr);
    fn(ptr);
    // Re-read HEAPU8 in case WASM memory grew during the call
    return m.HEAPU8.slice(ptr, ptr + data.byteLength);
  } finally {
    m._free(ptr);
  }
}

/**
 * Copies `data` into WASM memory, allocates a separate output buffer,
 * calls `fn(srcPtr, dstPtr)`, then returns the output bytes.
 */
function withSrcDstBuffers(
  m: PixelOpsModule,
  data: Uint8Array,
  dstByteLength: number,
  fn: (srcPtr: number, dstPtr: number) => void,
): Uint8Array {
  const srcPtr = m._malloc(data.byteLength);
  const dstPtr = m._malloc(dstByteLength);
  try {
    m.HEAPU8.set(data, srcPtr);
    fn(srcPtr, dstPtr);
    return m.HEAPU8.slice(dstPtr, dstPtr + dstByteLength);
  } finally {
    m._free(srcPtr);
    m._free(dstPtr);
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/** Flood-fill starting at (x, y) with the given RGBA colour.
 *  tolerance: max squared Euclidean distance in RGBA space (0 = exact match). */
export async function floodFill(
  pixels: Uint8Array,
  width: number,
  height: number,
  x: number,
  y: number,
  r: number,
  g: number,
  b: number,
  a: number,
  tolerance = 0,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withInPlaceBuffer(m, pixels, (ptr) =>
    m._pixelops_flood_fill(ptr, width, height, x, y, r, g, b, a, tolerance),
  );
}

/** Flood-fill for float32 RGBA layers (rgba32f).
 *  r/g/b/a are in [0,1] (may be >1 for HDR).
 *  tolerance: per-channel Euclidean threshold in [0,1] float space. */
export async function floodFillF32(
  pixels: Float32Array,
  width: number,
  height: number,
  x: number,
  y: number,
  r: number,
  g: number,
  b: number,
  a: number,
  tolerance = 0,
): Promise<Float32Array> {
  const m = await getPixelOps();
  const byteLen = pixels.byteLength;
  const ptr = m._malloc(byteLen);
  try {
    m.HEAPF32.set(pixels, ptr >> 2);
    m._pixelops_flood_fill_f32(ptr, width, height, x, y, r, g, b, a, tolerance);
    return new Float32Array(m.HEAPF32.buffer, ptr, pixels.length).slice();
  } finally {
    m._free(ptr);
  }
}

/** Generic 2-D convolution. kernelSize must be odd. src and dst are separate. */
export async function convolve(
  pixels: Uint8Array,
  width: number,
  height: number,
  kernel: Float32Array,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const kPtr = m._malloc(kernel.byteLength);
  try {
    m.HEAPF32.set(kernel, kPtr >> 2); // float32 view offset
    const kernelSize = Math.round(Math.sqrt(kernel.length));
    return withSrcDstBuffers(m, pixels, pixels.byteLength, (src, dst) =>
      m._pixelops_convolve(src, dst, width, height, kPtr, kernelSize),
    );
  } finally {
    m._free(kPtr);
  }
}

/** Bilinear resize — produces smooth edges (use for photographs). */
export async function resizeBilinear(
  pixels: Uint8Array,
  srcWidth: number,
  srcHeight: number,
  dstWidth: number,
  dstHeight: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withSrcDstBuffers(m, pixels, dstWidth * dstHeight * 4, (src, dst) =>
    m._pixelops_resize_bilinear(
      src,
      srcWidth,
      srcHeight,
      dst,
      dstWidth,
      dstHeight,
    ),
  );
}

/** Nearest-neighbour resize — preserves hard pixel-art edges. */
export async function resizeNearest(
  pixels: Uint8Array,
  srcWidth: number,
  srcHeight: number,
  dstWidth: number,
  dstHeight: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withSrcDstBuffers(m, pixels, dstWidth * dstHeight * 4, (src, dst) =>
    m._pixelops_resize_nearest(
      src,
      srcWidth,
      srcHeight,
      dst,
      dstWidth,
      dstHeight,
    ),
  );
}

/** Ordered (Bayer) dithering. matrixSize: 2, 4, or 8. */
export async function ditherBayer(
  pixels: Uint8Array,
  width: number,
  height: number,
  matrixSize: 2 | 4 | 8 = 4,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withInPlaceBuffer(m, pixels, (ptr) =>
    m._pixelops_dither_bayer(ptr, width, height, matrixSize),
  );
}

/** Median-cut palette quantisation.
 *  Returns an RGBA Uint8Array of `maxColors * 4` bytes
 *  and the actual count of palette entries. */
export async function quantize(
  pixels: Uint8Array,
  maxColors: number,
): Promise<{ palette: Uint8Array; count: number }> {
  const m = await getPixelOps();
  const pixelCount = pixels.length / 4;
  const palBuf = new Uint8Array(maxColors * 4);
  const pixPtr = m._malloc(pixels.byteLength);
  const palPtr = m._malloc(palBuf.byteLength);
  try {
    m.HEAPU8.set(pixels, pixPtr);
    const count = m._pixelops_quantize(pixPtr, pixelCount, palPtr, maxColors);
    const palette = m.HEAPU8.slice(palPtr, palPtr + count * 4);
    return { palette, count };
  } finally {
    m._free(pixPtr);
    m._free(palPtr);
  }
}

/** Compute histogram for curves adjustment.
 *  Returns RGB, Red, Green, Blue channel histograms (256 bins each).
 *  Optional selectionMask weights the contribution of each pixel. */
export async function computeHistogramRGBA(
  pixelData: Uint8Array,
  width: number,
  height: number,
  mask?: Uint8Array,
): Promise<CurvesHistogramResult> {
  const m = await getPixelOps();
  const pixPtr = m._malloc(pixelData.byteLength);
  let maskPtr = 0;
  try {
    m.HEAPU8.set(pixelData, pixPtr);
    if (mask) {
      maskPtr = m._malloc(mask.byteLength);
      m.HEAPU8.set(mask, maskPtr);
    }

    // Call WASM function to get histogram buffer pointer.
    const histPtr = m._pixelops_curves_histogram(
      pixPtr,
      width,
      height,
      maskPtr,
    );
    if (!histPtr) {
      throw new Error("WASM histogram allocation failed");
    }

    // Re-read HEAPF32 in case memory grew.
    const heapf32 = m.HEAPF32;
    const histFloatOffset = histPtr >> 2; // Convert byte offset to float32 offset.
    const histogramFloat32 = heapf32.slice(
      histFloatOffset,
      histFloatOffset + 4 * 256,
    );

    // Free the histogram buffer returned by WASM.
    m._free(histPtr);

    // Split into separate channels (each 256 float32s)
    const rgb = histogramFloat32.subarray(0, 256);
    const red = histogramFloat32.subarray(256, 512);
    const green = histogramFloat32.subarray(512, 768);
    const blue = histogramFloat32.subarray(768, 1024);

    return { rgb, red, green, blue };
  } finally {
    m._free(pixPtr);
    if (maskPtr) {
      m._free(maskPtr);
    }
  }
}

/**
 * Affine transform via inverse-mapping.
 * invMatrix: [a, b, tx, c, d, ty] — maps output (x,y) to source (u,v):
 *   u = a*x + b*y + tx
 *   v = c*x + d*y + ty
 * interp: 0=nearest, 1=bilinear, 2=bicubic
 */
export async function applyAffineTransform(
  src: Uint8Array,
  srcW: number,
  srcH: number,
  dstW: number,
  dstH: number,
  invMatrix: Float32Array,
  interp: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const matPtr = m._malloc(invMatrix.byteLength);
  try {
    m.HEAPF32.set(invMatrix, matPtr >> 2);
    return withSrcDstBuffers(m, src, dstW * dstH * 4, (srcPtr, dstPtr) =>
      m._pixelops_affine_transform(
        srcPtr,
        srcW,
        srcH,
        dstPtr,
        dstW,
        dstH,
        matPtr,
        interp,
      ),
    );
  } finally {
    m._free(matPtr);
  }
}

/**
 * Perspective transform via inverse 3×3 homography.
 * invH: 9 elements, row-major — maps output (x,y) to source (u,v) via:
 *   [u, v, w] = invH * [x, y, 1]ᵀ;  srcX = u/w, srcY = v/w
 * interp: 0=nearest, 1=bilinear, 2=bicubic
 */
export async function applyPerspectiveTransform(
  src: Uint8Array,
  srcW: number,
  srcH: number,
  dstW: number,
  dstH: number,
  invH: Float32Array,
  interp: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const matPtr = m._malloc(invH.byteLength);
  try {
    m.HEAPF32.set(invH, matPtr >> 2);
    return withSrcDstBuffers(m, src, dstW * dstH * 4, (srcPtr, dstPtr) =>
      m._pixelops_perspective_transform(
        srcPtr,
        srcW,
        srcH,
        dstPtr,
        dstW,
        dstH,
        matPtr,
        interp,
      ),
    );
  } finally {
    m._free(matPtr);
  }
}

/**
 * Rotate an RGBA image (4 bytes/pixel).
 * amount: 0 = 90°CW, 1 = 180°, 2 = 270°CW
 * Returns a new Uint8Array with dimensions swapped for 90/270, same for 180.
 */
export async function rotateRgba(
  src: Uint8Array,
  srcW: number,
  srcH: number,
  amount: 0 | 1 | 2,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const dstW = amount === 1 ? srcW : srcH;
  const dstH = amount === 1 ? srcH : srcW;
  return withSrcDstBuffers(m, src, dstW * dstH * 4, (srcPtr, dstPtr) =>
    m._pixelops_rotate_rgba(srcPtr, srcW, srcH, dstPtr, amount),
  );
}

/**
 * Flip an RGBA image (4 bytes/pixel).
 * axis: 0 = horizontal, 1 = vertical
 */
export async function flipRgba(
  src: Uint8Array,
  w: number,
  h: number,
  axis: 0 | 1,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withSrcDstBuffers(m, src, w * h * 4, (srcPtr, dstPtr) =>
    m._pixelops_flip_rgba(srcPtr, w, h, dstPtr, axis),
  );
}

/**
 * Rotate an indexed (1 byte/pixel) image.
 * amount: 0 = 90°CW, 1 = 180°, 2 = 270°CW
 */
export async function rotateIndexed(
  src: Uint8Array,
  srcW: number,
  srcH: number,
  amount: 0 | 1 | 2,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const dstLen = srcW * srcH; // same pixel count regardless of rotation
  return withSrcDstBuffers(m, src, dstLen, (srcPtr, dstPtr) =>
    m._pixelops_rotate_indexed(srcPtr, srcW, srcH, dstPtr, amount),
  );
}

/**
 * Flip an indexed (1 byte/pixel) image.
 * axis: 0 = horizontal, 1 = vertical
 */
export async function flipIndexed(
  src: Uint8Array,
  w: number,
  h: number,
  axis: 0 | 1,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withSrcDstBuffers(m, src, w * h, (srcPtr, dstPtr) =>
    m._pixelops_flip_indexed(srcPtr, w, h, dstPtr, axis),
  );
}

/**
 * Content-aware inpainting (PatchMatch).
 *
 * @param pixels   RGBA flat canvas composite, width × height × 4 bytes.
 * @param width    Canvas width in pixels.
 * @param height   Canvas height in pixels.
 * @param mask     Single-channel fill mask from activeScope().selection.mask,
 *                 width × height bytes (255 = fill region, 0 = source region).
 * @param sourceMask  Optional source-eligibility mask (1 = eligible, 0 = excluded).
 *                    Pass undefined for unconstrained (sample entire image).
 * @returns        RGBA output buffer, same dimensions as pixels.
 *                 Pixels outside the mask are unchanged copies of the input.
 */
export async function inpaintRegion(
  pixels: Uint8Array,
  width: number,
  height: number,
  mask: Uint8Array,
  sourceMask?: Uint8Array,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const PATCH_SIZE = 4; // → 9×9 patches
  const byteLen = pixels.byteLength; // width * height * 4

  const pixelsPtr = m._malloc(byteLen);
  const maskPtr = m._malloc(mask.byteLength);
  const outPtr = m._malloc(byteLen);
  let sourceMaskPtr = 0;
  try {
    m.HEAPU8.set(pixels, pixelsPtr);
    m.HEAPU8.set(mask, maskPtr);
    if (sourceMask !== undefined) {
      sourceMaskPtr = m._malloc(sourceMask.byteLength);
      m.HEAPU8.set(sourceMask, sourceMaskPtr);
    }
    m._pixelops_inpaint(
      pixelsPtr,
      width,
      height,
      maskPtr,
      PATCH_SIZE,
      sourceMaskPtr,
      outPtr,
    );
    // Re-read HEAPU8 in case WASM memory grew during the call
    return m.HEAPU8.slice(outPtr, outPtr + byteLen);
  } finally {
    m._free(pixelsPtr);
    m._free(maskPtr);
    if (sourceMaskPtr !== 0) m._free(sourceMaskPtr);
    m._free(outPtr);
  }
}

/**
 * GrabCut segmentation (Rother et al. 2004).
 *
 * @param pixels    RGBA image, width×height×4 bytes.
 * @param width     Image width.
 * @param height    Image height.
 * @param trimap    Per-pixel trimap: 0=BG, 128=unknown, 255=FG. width×height bytes.
 * @param iterations EM iterations (3 is typically sufficient).
 * @param k         GMM components per class (5 recommended).
 * @returns         Binary alpha mask (0 or 255), width×height bytes.
 */
export async function grabCut(
  pixels: Uint8Array,
  width: number,
  height: number,
  trimap: Uint8Array,
  iterations = 3,
  k = 5,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const n = width * height;

  const rgbaPtr = m._malloc(pixels.byteLength);
  const trimapPtr = m._malloc(n);
  const alphaPtr = m._malloc(n);
  try {
    m.HEAPU8.set(pixels, rgbaPtr);
    m.HEAPU8.set(trimap, trimapPtr);
    m._pixelops_grabcut(
      rgbaPtr,
      width,
      height,
      trimapPtr,
      alphaPtr,
      iterations,
      k,
    );
    // Re-read HEAPU8 in case WASM memory grew
    return m.HEAPU8.slice(alphaPtr, alphaPtr + n);
  } finally {
    m._free(rgbaPtr);
    m._free(trimapPtr);
    m._free(alphaPtr);
  }
}

// ─── GrabCut hybrid building blocks ──────────────────────────────────────────

/** Compute beta (1/2 contrast) for the image. */
export async function grabCutComputeBeta(
  pixels: Uint8Array,
  width: number,
  height: number,
): Promise<number> {
  const m = await getPixelOps();
  const rgbaPtr = m._malloc(pixels.byteLength);
  try {
    m.HEAPU8.set(pixels, rgbaPtr);
    return m._pixelops_grabcut_compute_beta(rgbaPtr, width, height);
  } finally {
    m._free(rgbaPtr);
  }
}

/** Initialise both GMMs from the trimap via k-means++.
 *  Returns a Float32Array of length 2*k*20 (FG first, then BG). */
export async function grabCutKmeansInit(
  pixels: Uint8Array,
  width: number,
  height: number,
  trimap: Uint8Array,
  k: number,
): Promise<Float32Array> {
  const m = await getPixelOps();
  const paramsLen = 2 * k * 20;
  const paramsBytes = paramsLen * 4;
  const rgbaPtr = m._malloc(pixels.byteLength);
  const trimapPtr = m._malloc(trimap.byteLength);
  const paramsPtr = m._malloc(paramsBytes);
  try {
    m.HEAPU8.set(pixels, rgbaPtr);
    m.HEAPU8.set(trimap, trimapPtr);
    m._pixelops_grabcut_kmeans_init(
      rgbaPtr,
      width,
      height,
      trimapPtr,
      k,
      paramsPtr,
    );
    const off = paramsPtr >> 2;
    return m.HEAPF32.slice(off, off + paramsLen);
  } finally {
    m._free(rgbaPtr);
    m._free(trimapPtr);
    m._free(paramsPtr);
  }
}

/** Re-estimate both GMMs given a binary label. Returns updated params. */
export async function grabCutUpdateGmms(
  pixels: Uint8Array,
  width: number,
  height: number,
  label: Uint8Array,
  k: number,
  params: Float32Array,
): Promise<Float32Array> {
  const m = await getPixelOps();
  const paramsLen = 2 * k * 20;
  const rgbaPtr = m._malloc(pixels.byteLength);
  const labelPtr = m._malloc(label.byteLength);
  const paramsPtr = m._malloc(params.byteLength);
  try {
    m.HEAPU8.set(pixels, rgbaPtr);
    m.HEAPU8.set(label, labelPtr);
    m.HEAPF32.set(params, paramsPtr >> 2);
    m._pixelops_grabcut_update_gmms(
      rgbaPtr,
      width,
      height,
      labelPtr,
      k,
      paramsPtr,
    );
    const off = paramsPtr >> 2;
    return m.HEAPF32.slice(off, off + paramsLen);
  } finally {
    m._free(rgbaPtr);
    m._free(labelPtr);
    m._free(paramsPtr);
  }
}

/** Run min-cut with externally-computed t-link and n-link arrays.
 *  Returns binary label (0 or 1) per pixel, width*height bytes. */
export async function grabCutMincut(
  capS: Float32Array,
  capT: Float32Array,
  hW: Float32Array,
  vW: Float32Array,
  trimap: Uint8Array,
  width: number,
  height: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const n = width * height;
  const capSPtr = m._malloc(capS.byteLength);
  const capTPtr = m._malloc(capT.byteLength);
  const hWPtr = m._malloc(hW.byteLength);
  const vWPtr = m._malloc(vW.byteLength);
  const trimapPtr = m._malloc(trimap.byteLength);
  const labelPtr = m._malloc(n);
  try {
    m.HEAPF32.set(capS, capSPtr >> 2);
    m.HEAPF32.set(capT, capTPtr >> 2);
    m.HEAPF32.set(hW, hWPtr >> 2);
    m.HEAPF32.set(vW, vWPtr >> 2);
    m.HEAPU8.set(trimap, trimapPtr);
    m._pixelops_grabcut_mincut(
      capSPtr,
      capTPtr,
      hWPtr,
      vWPtr,
      trimapPtr,
      width,
      height,
      labelPtr,
    );
    return m.HEAPU8.slice(labelPtr, labelPtr + n);
  } finally {
    m._free(capSPtr);
    m._free(capTPtr);
    m._free(hWPtr);
    m._free(vWPtr);
    m._free(trimapPtr);
    m._free(labelPtr);
  }
}

/** Maps each RGBA8 pixel to the nearest palette index (squared Euclidean distance in RGBA space).
 *  Transparent pixels (alpha == 0) are assigned transparentIdx.
 *  Returns a Uint8Array of length pixelCount containing one palette index per pixel. */
export async function matchPaletteIndices(
  rgba: Uint8Array,
  palette: Array<{ r: number; g: number; b: number; a: number }>,
  transparentIdx = 255,
): Promise<Uint8Array> {
  const palFlat = new Uint8Array(palette.length * 4);
  palette.forEach((c, i) => {
    palFlat[i * 4] = c.r;
    palFlat[i * 4 + 1] = c.g;
    palFlat[i * 4 + 2] = c.b;
    palFlat[i * 4 + 3] = c.a;
  });

  const m = await getPixelOps();
  const pixelCount = rgba.length / 4;

  const rgbaPtr = m._malloc(rgba.byteLength);
  const palPtr = m._malloc(Math.max(palFlat.byteLength, 1));
  const outPtr = m._malloc(pixelCount);
  try {
    m.HEAPU8.set(rgba, rgbaPtr);
    if (palFlat.byteLength > 0) m.HEAPU8.set(palFlat, palPtr);
    m._matchPaletteIndices(
      rgbaPtr,
      pixelCount,
      palPtr,
      palette.length,
      outPtr,
      transparentIdx,
    );
    // Re-read HEAPU8 in case WASM memory grew during the call
    return m.HEAPU8.slice(outPtr, outPtr + pixelCount);
  } finally {
    m._free(rgbaPtr);
    m._free(palPtr);
    m._free(outPtr);
  }
}

/**
 * BFS 4-connected flood fill on a 1-byte-per-pixel indexed layer buffer.
 * Replaces all pixels connected to (startX, startY) that share the same
 * starting index with fillIndex.  Operates in-place; the modified indices
 * are written back to the provided buffer.
 */
export async function floodFillIndexed(
  indices: Uint8Array,
  w: number,
  h: number,
  startX: number,
  startY: number,
  fillIndex: number,
): Promise<void> {
  const m = await getPixelOps();
  const ptr = m._malloc(indices.byteLength);
  try {
    m.HEAPU8.set(indices, ptr);
    m._floodFillIndexed(ptr, w, h, startX, startY, fillIndex);
    // Re-read HEAPU8 in case WASM memory grew during the call
    indices.set(m.HEAPU8.subarray(ptr, ptr + indices.byteLength));
  } finally {
    m._free(ptr);
  }
}

// ─── EXR I/O ─────────────────────────────────────────────────────────────────

/** Decode an OpenEXR file. */
export async function decodeExr(
  bytes: Uint8Array,
): Promise<{ pixels: Float32Array; width: number; height: number }> {
  const m = await getPixelOps();
  const srcPtr = m._malloc(bytes.byteLength);
  try {
    m.HEAPU8.set(bytes, srcPtr);
    const resultPtr = m._loadExr(srcPtr, bytes.byteLength);
    if (resultPtr === 0) throw new Error("EXR decode failed");
    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    const width = view.getInt32(resultPtr, true);
    const height = view.getInt32(resultPtr + 4, true);
    const pxPtr = view.getInt32(resultPtr + 8, true);
    const count = width * height * 4;
    const pixels = new Float32Array(count);
    const heap = new Float32Array(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    pixels.set(heap.subarray(pxPtr >> 2, (pxPtr >> 2) + count));
    m._freeExrResult(resultPtr);
    return { pixels, width, height };
  } finally {
    m._free(srcPtr);
  }
}

/** Encode RGBA float32 pixels to OpenEXR. compression: 0=none,1=zip,2=zips,3=piz; halfFloat: 0 or 1. */
export async function encodeExr(
  pixels: Float32Array,
  width: number,
  height: number,
  compression = 0,
  halfFloat = 0,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const srcPtr = m._malloc(pixels.byteLength);
  try {
    new Float32Array(
      m.HEAPU8.buffer,
      m.HEAPU8.byteOffset + srcPtr,
      pixels.length,
    ).set(pixels);
    const resultPtr = m._saveExr(srcPtr, width, height, compression, halfFloat);
    if (resultPtr === 0) throw new Error("EXR encode failed");
    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    const bytesPtr = view.getInt32(resultPtr, true);
    const outLen = view.getInt32(resultPtr + 4, true);
    const out = new Uint8Array(outLen);
    out.set(m.HEAPU8.subarray(bytesPtr, bytesPtr + outLen));
    m._freeExrBytes(resultPtr);
    return out;
  } finally {
    m._free(srcPtr);
  }
}

export interface ExrDecodedLayer {
  name: string;
  width: number;
  height: number;
  offsetX: number;
  offsetY: number;
  pixels: Float32Array;
}

export interface ExrMultiDecodeResult {
  canvasWidth: number;
  canvasHeight: number;
  layers: ExrDecodedLayer[];
}

/** Read a null-terminated UTF-8 string from the WASM heap. */
function readCString(heap: Uint8Array, ptr: number): string {
  let end = ptr;
  while (end < heap.length && heap[end] !== 0) end++;
  return new TextDecoder("utf-8").decode(heap.subarray(ptr, end));
}

/** Decode an EXR file into one or more named layers. */
export async function decodeExrLayers(
  bytes: Uint8Array,
): Promise<ExrMultiDecodeResult> {
  const m = await getPixelOps();
  const srcPtr = m._malloc(bytes.byteLength);
  let resultPtr = 0;
  try {
    m.HEAPU8.set(bytes, srcPtr);
    resultPtr = m._loadExrLayers(srcPtr, bytes.byteLength);
    if (resultPtr === 0) throw new Error("EXR multi-layer decode failed");

    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    const canvasWidth = view.getInt32(resultPtr, true);
    const canvasHeight = view.getInt32(resultPtr + 4, true);
    const numLayers = view.getInt32(resultPtr + 8, true);
    const layersPtr = view.getInt32(resultPtr + 12, true);

    const layers: ExrDecodedLayer[] = [];
    const STRIDE = 24; // ExrLayerOut size
    for (let i = 0; i < numLayers; i++) {
      const base = layersPtr + i * STRIDE;
      const w = view.getInt32(base, true);
      const h = view.getInt32(base + 4, true);
      const offX = view.getInt32(base + 8, true);
      const offY = view.getInt32(base + 12, true);
      const namePtr = view.getInt32(base + 16, true);
      const pxPtr = view.getInt32(base + 20, true);
      const name = readCString(m.HEAPU8, namePtr);
      const count = w * h * 4;
      const pixels = new Float32Array(count);
      const heapF32 = new Float32Array(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
      pixels.set(heapF32.subarray(pxPtr >> 2, (pxPtr >> 2) + count));
      layers.push({
        name,
        width: w,
        height: h,
        offsetX: offX,
        offsetY: offY,
        pixels,
      });
    }
    return { canvasWidth, canvasHeight, layers };
  } finally {
    if (resultPtr !== 0) m._freeExrLayersResult(resultPtr);
    m._free(srcPtr);
  }
}

/**
 * Encode multiple full-canvas RGBA float32 layers into a single-part EXR with
 * channel-named groups ("<LayerName>.R/G/B/A").  Each layer's `pixels` must be
 * width*height*4 floats.
 */
export async function encodeExrLayers(
  layers: ReadonlyArray<{ name: string; pixels: Float32Array }>,
  width: number,
  height: number,
  compression = 0,
  halfFloat = 0,
): Promise<Uint8Array> {
  if (layers.length === 0) throw new Error("encodeExrLayers: no layers given");
  const m = await getPixelOps();

  // Pack names: null-separated UTF-8.
  const enc = new TextEncoder();
  const nameBufs = layers.map((l) => enc.encode(l.name));
  const nameBytes = nameBufs.reduce((s, b) => s + b.length + 1, 0);
  const namesBuf = new Uint8Array(nameBytes);
  {
    let off = 0;
    for (const nb of nameBufs) {
      namesBuf.set(nb, off);
      off += nb.length;
      namesBuf[off++] = 0;
    }
  }

  // Pack pixels: layer-major contiguous.
  const pixelsPerLayer = width * height * 4;
  const totalFloats = pixelsPerLayer * layers.length;
  const namesPtr = m._malloc(namesBuf.byteLength);
  const pixelsPtr = m._malloc(totalFloats * 4);
  let resultPtr = 0;
  try {
    m.HEAPU8.set(namesBuf, namesPtr);
    const heapF32 = new Float32Array(
      m.HEAPU8.buffer,
      m.HEAPU8.byteOffset + pixelsPtr,
      totalFloats,
    );
    for (let i = 0; i < layers.length; i++) {
      if (layers[i].pixels.length !== pixelsPerLayer) {
        throw new Error(
          `encodeExrLayers: layer ${i} (${layers[i].name}) has ${layers[i].pixels.length} floats, expected ${pixelsPerLayer}`,
        );
      }
      heapF32.set(layers[i].pixels, i * pixelsPerLayer);
    }
    resultPtr = m._saveExrLayers(
      width,
      height,
      layers.length,
      namesPtr,
      pixelsPtr,
      compression,
      halfFloat,
    );
    if (resultPtr === 0) throw new Error("EXR multi-layer encode failed");
    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    const bytesPtr = view.getInt32(resultPtr, true);
    const outLen = view.getInt32(resultPtr + 4, true);
    const out = new Uint8Array(outLen);
    out.set(m.HEAPU8.subarray(bytesPtr, bytesPtr + outLen));
    return out;
  } finally {
    if (resultPtr !== 0) m._freeExrBytes(resultPtr);
    m._free(namesPtr);
    m._free(pixelsPtr);
  }
}

// ─── DDS I/O ─────────────────────────────────────────────────────────────────

export const DdsFormat = {
  BC1: 1,
  BC2: 2,
  BC3: 3,
  BC4: 4,
  BC5: 5,
  BC6H: 6,
  BC7: 7,
  RGBA8: 8,
  RGBA32F: 9,
} as const;
export type DdsFormat = (typeof DdsFormat)[keyof typeof DdsFormat];

export const DdsHeaderMode = {
  AUTO: 0,
  DX9: 1,
  DX10: 2,
} as const;

export interface DdsInfo {
  width: number;
  height: number;
  fmt: DdsFormat;
  mipLevels: number;
}

function ddsErrorFromCode(code: number): string {
  switch (code) {
    case -1:
      return "DDS: invalid file";
    case -2:
      return "DDS: unsupported format";
    case -3:
      return "DDS: output buffer too small";
    default:
      return `DDS: error code ${code}`;
  }
}

/** Parse DDS header metadata. */
export async function getDdsInfo(bytes: Uint8Array): Promise<DdsInfo> {
  const m = await getPixelOps();
  const dataPtr = m._malloc(bytes.byteLength);
  const outPtr = m._malloc(16); // 4 × int32
  try {
    m.HEAPU8.set(bytes, dataPtr);
    const err = m._pixelops_dds_get_info(dataPtr, bytes.byteLength, outPtr);
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    return {
      width: view.getInt32(outPtr, true),
      height: view.getInt32(outPtr + 4, true),
      fmt: view.getInt32(outPtr + 8, true) as DdsFormat,
      mipLevels: view.getInt32(outPtr + 12, true),
    };
  } finally {
    m._free(dataPtr);
    m._free(outPtr);
  }
}

/** Decode a DDS file to RGBA8 pixels. BC6H and RGBA32F are tonemapped to SDR. */
export async function decodeDds(
  bytes: Uint8Array,
): Promise<{ pixels: Uint8Array; width: number; height: number }> {
  const m = await getPixelOps();
  const info = await getDdsInfo(bytes);
  const { width, height } = info;
  const outSize = width * height * 4;
  const dataPtr = m._malloc(bytes.byteLength);
  const outPtr = m._malloc(outSize);
  try {
    m.HEAPU8.set(bytes, dataPtr);
    const err = m._pixelops_dds_decode(
      dataPtr,
      bytes.byteLength,
      outPtr,
      outSize,
    );
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const pixels = new Uint8Array(outSize);
    pixels.set(m.HEAPU8.subarray(outPtr, outPtr + outSize));
    return { pixels, width, height };
  } finally {
    m._free(dataPtr);
    m._free(outPtr);
  }
}

/** Decode a DDS file to RGBA float32 pixels. */
export async function decodeDdsF32(
  bytes: Uint8Array,
): Promise<{ pixels: Float32Array; width: number; height: number }> {
  const m = await getPixelOps();
  const info = await getDdsInfo(bytes);
  const { width, height } = info;
  const outSize = width * height * 16; // 4 floats × 4 bytes
  const dataPtr = m._malloc(bytes.byteLength);
  const outPtr = m._malloc(outSize);
  try {
    m.HEAPU8.set(bytes, dataPtr);
    const err = m._pixelops_dds_decode_f32(
      dataPtr,
      bytes.byteLength,
      outPtr,
      outSize,
    );
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const pixels = new Float32Array(width * height * 4);
    const heap = new Float32Array(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    pixels.set(heap.subarray(outPtr >> 2, (outPtr >> 2) + pixels.length));
    return { pixels, width, height };
  } finally {
    m._free(dataPtr);
    m._free(outPtr);
  }
}

/** Encode RGBA8 pixels to a DDS file (BC1, BC3, BC7). */
export async function encodeDds(
  pixels: Uint8Array,
  width: number,
  height: number,
  fmt: number,
  mipLevels: number = 1,
  headerMode: number = DdsHeaderMode.AUTO,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const outSize = m._pixelops_dds_get_encoded_size(
    width,
    height,
    fmt,
    mipLevels,
    headerMode,
  );
  if (outSize <= 0) throw new Error(ddsErrorFromCode(outSize));
  const srcPtr = m._malloc(pixels.byteLength);
  const outPtr = m._malloc(outSize);
  try {
    m.HEAPU8.set(pixels, srcPtr);
    const err = m._pixelops_dds_encode(
      srcPtr,
      width,
      height,
      fmt,
      mipLevels,
      headerMode,
      outPtr,
      outSize,
    );
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const out = new Uint8Array(outSize);
    out.set(m.HEAPU8.subarray(outPtr, outPtr + outSize));
    return out;
  } finally {
    m._free(srcPtr);
    m._free(outPtr);
  }
}

/** Encode RGBA float32 pixels to a DDS file (BC6H UF16 or raw RGBA32F). */
export async function encodeDdsF32(
  pixels: Float32Array,
  width: number,
  height: number,
  fmt: number,
  mipLevels: number = 1,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const outSize = m._pixelops_dds_get_encoded_size(
    width,
    height,
    fmt,
    mipLevels,
    DdsHeaderMode.DX10,
  );
  if (outSize <= 0) throw new Error(ddsErrorFromCode(outSize));
  const srcPtr = m._malloc(pixels.byteLength);
  const outPtr = m._malloc(outSize);
  try {
    new Float32Array(
      m.HEAPU8.buffer,
      m.HEAPU8.byteOffset + srcPtr,
      pixels.length,
    ).set(pixels);
    const err = m._pixelops_dds_encode_f32(
      srcPtr,
      width,
      height,
      fmt,
      mipLevels,
      DdsHeaderMode.DX10,
      outPtr,
      outSize,
    );
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const out = new Uint8Array(outSize);
    // Re-read HEAPU8 in case WASM memory grew
    out.set(m.HEAPU8.subarray(outPtr, outPtr + outSize));
    return out;
  } finally {
    m._free(srcPtr);
    m._free(outPtr);
  }
}

/** Maximum mip levels such that the smallest dimension is >= minDim. */
export async function maxDdsMipLevels(
  width: number,
  height: number,
  minDim: number,
): Promise<number> {
  const m = await getPixelOps();
  return m._pixelops_dds_max_mip_levels(width, height, minDim);
}
