/**
 * src/wasm/index.ts
 *
 * Async wrapper around the Emscripten pixelops WASM module.
 *
 * SETUP REQUIRED — before this module works you must compile the WASM:
 *   npm run build:wasm
 * This generates src/wasm/generated/pixelops.js and pixelops.wasm.
 *
 * Usage:
 *   import { getPixelOps, floodFill } from '@/wasm'
 *   const wasmReady = getPixelOps() // call once; subsequent calls return cache
 */

import type {
  PixelOpsModule,
  PixelOpsFactory,
  CurvesHistogramResult,
} from "./types";
import { syncIfGrew } from "./wasmHeapStorage";
import { notificationStore } from "@/core/store/notificationStore";

// ─── Module singleton ─────────────────────────────────────────────────────────

let _module: PixelOpsModule | null = null;
let _initPromise: Promise<PixelOpsModule> | null = null;

/**
 * Synchronous accessor — returns the cached module if it's already loaded,
 * `null` otherwise. Lets sync hot paths (brush stamp engine) use WASM
 * opportunistically and fall back to JS until the async load completes.
 * Pair with `kickoffPixelOpsLoad()` at app startup so the cache is warm
 * before the first paint.
 */
export function getPixelOpsSync(): PixelOpsModule | null {
  return _module;
}

/** Fire-and-forget the WASM load so subsequent `getPixelOpsSync` calls
 *  succeed. Safe to call multiple times — the underlying loader is
 *  cached. Errors are swallowed (sync callers handle null gracefully). */
export function kickoffPixelOpsLoad(): void {
  void getPixelOps().catch(() => {});
}

/** Initialise and return the WASM module (idempotent, cached after first call). */
export async function getPixelOps(): Promise<PixelOpsModule> {
  if (_module) return _module;
  if (_initPromise) return _initPromise;

  _initPromise = (async () => {
    // Dynamic import so Vite only bundles these when getPixelOps() is called.
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — file is generated by `npm run build:wasm`
    const { default: factory } = (await import("./generated/pixelops.js")) as {
      default: PixelOpsFactory;
    };
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore — generated asset URL resolved by Vite
    const wasmUrl = (await import("./generated/pixelops.wasm?url"))
      .default as string;

    _module = await factory({ locateFile: () => wasmUrl });
    installWasm64Wrappers(_module);
    return _module;
  })();

  return _initPromise;
}

// ─── wasm64 boundary ──────────────────────────────────────────────────────────
//
// The WASM module is compiled with `-sMEMORY64=2` (wasm64) so the heap can
// grow past the wasm32 4 GB cap (we target 16 GB max). Under wasm64, the
// JS↔WASM boundary uses BigInt for every i64-typed value — that's every
// pointer (`void*`, `uint8_t*`, …) plus `size_t` (so `_malloc(size)` takes
// a BigInt and returns a BigInt).
//
// The rest of the TS code (brushStamp.ts, wasmHeapStorage.ts, all the
// operations below, layer.wasmPtr on GpuLayer, …) treats pointers as plain
// `number`. We keep that invariant by wrapping every export at module-init:
// the wrapper converts Number→BigInt on the way in for pointer args, and
// BigInt→Number on the way out for pointer returns. Number is safe because
// 16 GB = 2^34 fits well inside Number.MAX_SAFE_INTEGER (2^53).
//
// Anything that needs the WASM heap byte-offset of a typed-array view stays
// Number-side — typed-array constructors and HEAPU8/HEAPF32.set() accept
// Number offsets up to the buffer length (16 GB is well below 2^53 too).

/** Wrap an export so the indexes in `ptrArgs` are converted Number→BigInt
 *  before the call, and the return value is converted BigInt→Number when
 *  `ptrReturn` is true. `BigInt(undefined)` throws — coerce missing args to
 *  0 defensively (matches the C++ side's null-ptr semantics). */
/** The module whose exports are being wrapped (set by installWasm64Wrappers). */
let wrappedModule: PixelOpsModule | null = null;

/** Thrown when the WASM heap can't satisfy an allocation. */
export class WasmOutOfMemoryError extends Error {
  constructor(public readonly requestedBytes: number) {
    super(
      `Out of memory: the image-processing engine could not allocate ` +
        `${(requestedBytes / (1024 * 1024)).toFixed(1)} MB. ` +
        `Close other documents or reduce the image size and try again.`,
    );
    this.name = "WasmOutOfMemoryError";
  }
}

/**
 * A C++ abort (e.g. std::bad_alloc) kills the module for good: every later
 * call throws. It can't be transparently re-created, because pinned layer
 * buffers live in the dead module's heap and freeing them through a new
 * instance would corrupt it. Tell the user once so they can save and
 * restart, instead of a string of unexplained failures.
 */
let abortReported = false;
function reportAbort(err: unknown): void {
  if (abortReported || !(err instanceof WebAssembly.RuntimeError)) return;
  abortReported = true;
  console.error("[wasm] Module aborted:", err);
  notificationStore.error(
    "The image-processing engine stopped working (" +
      err.message +
      "). Save your work and restart Verve.",
  );
}

function wrapPtrFn<F extends (...args: never[]) => unknown>(
  fn: F,
  ptrArgs: readonly number[],
  ptrReturn: boolean,
): F {
  const raw = fn as unknown as (...a: unknown[]) => unknown;
  return ((...args: unknown[]) => {
    for (const i of ptrArgs) {
      const v = args[i];
      args[i] = typeof v === "bigint" ? v : BigInt((v as number | undefined) ?? 0);
    }
    let r: unknown;
    try {
      r = raw(...args);
    } catch (err) {
      reportAbort(err);
      throw err;
    }
    // C++ can grow the heap itself (std::vector in inpaint, grabcut, EXR,
    // quantize…). Growth detaches every pinned `layer.data` view, and they
    // used to stay detached until some later JS `_malloc` happened to call
    // syncIfGrew. Re-bind right after every call — one identity compare
    // when nothing grew.
    if (wrappedModule) syncIfGrew(wrappedModule);
    return ptrReturn ? Number(r as bigint) : r;
  }) as unknown as F;
}

/** Install Number↔BigInt-converting wrappers around every export that
 *  takes or returns an i64 (pointer or size_t). Called once, right after
 *  the Emscripten factory resolves. */
function installWasm64Wrappers(m: PixelOpsModule): void {
  wrappedModule = m;
  // _malloc: size_t arg + ptr return are both i64. Also triggers
  // `syncIfGrew` so any allocation that grew the heap rebinds the
  // typed-array views tracked by `wasmHeapStorage`. Without this, views
  // handed out by `allocWasmU8/F32` become detached and the next `.set()`
  // throws "detached ArrayBuffer".
  const origMalloc = m._malloc;
  m._malloc = ((size: number): number => {
    const ptr = Number((origMalloc as unknown as (s: bigint) => bigint).call(m, BigInt(size)));
    syncIfGrew(m);
    // With ALLOW_MEMORY_GROWTH Emscripten's malloc returns 0 on failure
    // instead of aborting. Callers then wrote their input at address 0,
    // silently corrupting static data and the stack. Fail loudly instead.
    if (ptr === 0 && size > 0) {
      throw new WasmOutOfMemoryError(size);
    }
    return ptr;
  }) as typeof m._malloc;

  m._free = wrapPtrFn(m._free, [0], false);

  m._pixelops_flood_fill = wrapPtrFn(m._pixelops_flood_fill, [0], false);
  m._pixelops_flood_fill_f32 = wrapPtrFn(m._pixelops_flood_fill_f32, [0], false);
  m._pixelops_resize_bilinear = wrapPtrFn(m._pixelops_resize_bilinear, [0, 3], false);
  m._pixelops_resize_nearest = wrapPtrFn(m._pixelops_resize_nearest, [0, 3], false);
  m._pixelops_quantize = wrapPtrFn(m._pixelops_quantize, [0, 2], false);
  m._pixelops_curves_histogram = wrapPtrFn(m._pixelops_curves_histogram, [0, 3], true);
  m._pixelops_affine_transform = wrapPtrFn(m._pixelops_affine_transform, [0, 3, 6], false);
  m._pixelops_perspective_transform = wrapPtrFn(m._pixelops_perspective_transform, [0, 3, 6], false);
  m._pixelops_rotate_rgba = wrapPtrFn(m._pixelops_rotate_rgba, [0, 3], false);
  m._pixelops_flip_rgba = wrapPtrFn(m._pixelops_flip_rgba, [0, 3], false);
  m._pixelops_rotate_indexed = wrapPtrFn(m._pixelops_rotate_indexed, [0, 3], false);
  m._pixelops_flip_indexed = wrapPtrFn(m._pixelops_flip_indexed, [0, 3], false);
  m._pixelops_inpaint = wrapPtrFn(m._pixelops_inpaint, [0, 3, 5, 6], false);
  m._pixelops_grabcut = wrapPtrFn(m._pixelops_grabcut, [0, 3, 4], false);
  m._pixelops_grabcut_compute_beta = wrapPtrFn(m._pixelops_grabcut_compute_beta, [0], false);
  m._pixelops_grabcut_kmeans_init = wrapPtrFn(m._pixelops_grabcut_kmeans_init, [0, 3, 5], false);
  m._pixelops_grabcut_update_gmms = wrapPtrFn(m._pixelops_grabcut_update_gmms, [0, 3, 5], false);
  m._pixelops_grabcut_mincut = wrapPtrFn(m._pixelops_grabcut_mincut, [0, 1, 2, 3, 4, 7], false);
  m._matchPaletteIndices = wrapPtrFn(m._matchPaletteIndices, [0, 2, 4], false);

  m._loadExr = wrapPtrFn(m._loadExr, [0], true);
  m._freeExrResult = wrapPtrFn(m._freeExrResult, [0], false);
  m._saveExr = wrapPtrFn(m._saveExr, [0], true);
  m._freeExrBytes = wrapPtrFn(m._freeExrBytes, [0], false);
  m._loadExrLayers = wrapPtrFn(m._loadExrLayers, [0], true);
  m._freeExrLayersResult = wrapPtrFn(m._freeExrLayersResult, [0], false);
  m._saveExrLayers = wrapPtrFn(m._saveExrLayers, [3, 4], true);

  m._pixelops_dds_get_info = wrapPtrFn(m._pixelops_dds_get_info, [0, 2], false);
  m._pixelops_dds_decode = wrapPtrFn(m._pixelops_dds_decode, [0, 2], false);
  m._pixelops_dds_decode_f32 = wrapPtrFn(m._pixelops_dds_decode_f32, [0, 2], false);
  // _pixelops_dds_get_encoded_size + _pixelops_dds_max_mip_levels take only
  // `int32_t`/`int` args and return `int32_t`/`int` — no i64 conversion.
  m._pixelops_dds_encode = wrapPtrFn(m._pixelops_dds_encode, [0, 6], false);
  m._pixelops_dds_encode_f32 = wrapPtrFn(m._pixelops_dds_encode_f32, [0, 6], false);

  m._pixelops_brush_stamp = wrapPtrFn(m._pixelops_brush_stamp, [0, 1, 2, 3, 4, 7], false);
  m._pixelops_brush_stamp_batch = wrapPtrFn(m._pixelops_brush_stamp_batch, [0, 2, 3, 4, 5, 8], false);
  m._pixelops_brush_bake_coverage = wrapPtrFn(m._pixelops_brush_bake_coverage, [0, 1, 4, 7], false);
  m._pixelops_brush_stamp_bitmap = wrapPtrFn(m._pixelops_brush_stamp_bitmap, [0, 1, 2, 3, 4], false);
  m._pixelops_brush_stamp_bitmap_batch = wrapPtrFn(m._pixelops_brush_stamp_bitmap_batch, [0, 2, 3, 4, 5], false);

  // ── lcms2 colour management (optional — only present when vendored) ──
  if (typeof m._cms_get_working_profile === "function") {
    // returns a ptr (i64) and takes an out-size ptr (i64).
    m._cms_get_working_profile = wrapPtrFn(
      m._cms_get_working_profile,
      [1],
      true,
    );
    m._cms_free_buffer = wrapPtrFn(m._cms_free_buffer!, [0], false);
    m._cms_create_transform = wrapPtrFn(
      m._cms_create_transform!,
      [0, 2],
      true,
    );
    m._cms_transform_apply = wrapPtrFn(
      m._cms_transform_apply!,
      [0, 1, 2],
      false,
    );
    m._cms_destroy_transform = wrapPtrFn(m._cms_destroy_transform!, [0], false);
    m._cms_build_3d_lut = wrapPtrFn(m._cms_build_3d_lut!, [0, 6], false);
    if (typeof m._cms_build_proof_lut === "function") {
      // Ptr args: proofProfilePtr(0), displayProfilePtr(2), outPtr(13).
      m._cms_build_proof_lut = wrapPtrFn(
        m._cms_build_proof_lut,
        [0, 2, 13],
        false,
      );
    }
  }
}

// ─── Memory helpers ───────────────────────────────────────────────────────────

/**
 * Copies `data` into WASM memory, calls `fn(ptr)` which may modify it in-place,
 * then copies the (possibly modified) bytes back out and frees the WASM allocation.
 */
function withInPlaceBuffer(
  m: PixelOpsModule,
  data: Uint8Array,
  fn: (ptr: number) => void,
): Uint8Array {
  const ptr = m._malloc(data.byteLength);
  try {
    m.HEAPU8.set(data, ptr);
    fn(ptr);
    // Re-read HEAPU8 in case WASM memory grew during the call
    return m.HEAPU8.slice(ptr, ptr + data.byteLength);
  } finally {
    m._free(ptr);
  }
}

/**
 * Copies `data` into WASM memory, allocates a separate output buffer,
 * calls `fn(srcPtr, dstPtr)`, then returns the output bytes.
 */
function withSrcDstBuffers(
  m: PixelOpsModule,
  data: Uint8Array,
  dstByteLength: number,
  fn: (srcPtr: number, dstPtr: number) => void,
): Uint8Array {
  const srcPtr = m._malloc(data.byteLength);
  const dstPtr = m._malloc(dstByteLength);
  try {
    m.HEAPU8.set(data, srcPtr);
    fn(srcPtr, dstPtr);
    return m.HEAPU8.slice(dstPtr, dstPtr + dstByteLength);
  } finally {
    m._free(srcPtr);
    m._free(dstPtr);
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/** Flood-fill starting at (x, y) with the given RGBA colour.
 *  tolerance: max squared Euclidean distance in RGBA space (0 = exact match). */
export async function floodFill(
  pixels: Uint8Array,
  width: number,
  height: number,
  x: number,
  y: number,
  r: number,
  g: number,
  b: number,
  a: number,
  tolerance = 0,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withInPlaceBuffer(m, pixels, (ptr) =>
    m._pixelops_flood_fill(ptr, width, height, x, y, r, g, b, a, tolerance),
  );
}

/** Flood-fill for float32 RGBA layers (rgba32f).
 *  r/g/b/a are in [0,1] (may be >1 for HDR).
 *  tolerance: per-channel Euclidean threshold in [0,1] float space. */
export async function floodFillF32(
  pixels: Float32Array,
  width: number,
  height: number,
  x: number,
  y: number,
  r: number,
  g: number,
  b: number,
  a: number,
  tolerance = 0,
): Promise<Float32Array> {
  const m = await getPixelOps();
  const byteLen = pixels.byteLength;
  const ptr = m._malloc(byteLen);
  try {
    m.HEAPF32.set(pixels, ptr / 4);
    m._pixelops_flood_fill_f32(ptr, width, height, x, y, r, g, b, a, tolerance);
    return new Float32Array(m.HEAPF32.buffer, ptr, pixels.length).slice();
  } finally {
    m._free(ptr);
  }
}

/** Bilinear resize — produces smooth edges (use for photographs). */
export async function resizeBilinear(
  pixels: Uint8Array,
  srcWidth: number,
  srcHeight: number,
  dstWidth: number,
  dstHeight: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withSrcDstBuffers(m, pixels, dstWidth * dstHeight * 4, (src, dst) =>
    m._pixelops_resize_bilinear(
      src,
      srcWidth,
      srcHeight,
      dst,
      dstWidth,
      dstHeight,
    ),
  );
}

/** Nearest-neighbour resize — preserves hard pixel-art edges. */
export async function resizeNearest(
  pixels: Uint8Array,
  srcWidth: number,
  srcHeight: number,
  dstWidth: number,
  dstHeight: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withSrcDstBuffers(m, pixels, dstWidth * dstHeight * 4, (src, dst) =>
    m._pixelops_resize_nearest(
      src,
      srcWidth,
      srcHeight,
      dst,
      dstWidth,
      dstHeight,
    ),
  );
}

/** Median-cut palette quantisation.
 *  Returns an RGBA Uint8Array of `maxColors * 4` bytes
 *  and the actual count of palette entries. */
export async function quantize(
  pixels: Uint8Array,
  maxColors: number,
): Promise<{ palette: Uint8Array; count: number }> {
  assertBytes("quantize", pixels);
  const m = await getPixelOps();
  const pixelCount = pixels.length / 4;
  const palBuf = new Uint8Array(maxColors * 4);
  const pixPtr = m._malloc(pixels.byteLength);
  const palPtr = m._malloc(palBuf.byteLength);
  try {
    m.HEAPU8.set(pixels, pixPtr);
    const count = m._pixelops_quantize(pixPtr, pixelCount, palPtr, maxColors);
    const palette = m.HEAPU8.slice(palPtr, palPtr + count * 4);
    return { palette, count };
  } finally {
    m._free(pixPtr);
    m._free(palPtr);
  }
}

/** Compute histogram for curves adjustment.
 *  Returns RGB, Red, Green, Blue channel histograms (256 bins each).
 *  Optional selectionMask weights the contribution of each pixel. */
export async function computeHistogramRGBA(
  pixelData: Uint8Array,
  width: number,
  height: number,
  mask?: Uint8Array,
): Promise<CurvesHistogramResult> {
  const m = await getPixelOps();
  const pixPtr = m._malloc(pixelData.byteLength);
  let maskPtr = 0;
  try {
    m.HEAPU8.set(pixelData, pixPtr);
    if (mask) {
      maskPtr = m._malloc(mask.byteLength);
      m.HEAPU8.set(mask, maskPtr);
    }

    // Call WASM function to get histogram buffer pointer.
    const histPtr = m._pixelops_curves_histogram(
      pixPtr,
      width,
      height,
      maskPtr,
    );
    if (!histPtr) {
      throw new Error("WASM histogram allocation failed");
    }

    // Re-read HEAPF32 in case memory grew.
    const heapf32 = m.HEAPF32;
    const histFloatOffset = histPtr / 4; // Convert byte offset to float32 offset.
    const histogramFloat32 = heapf32.slice(
      histFloatOffset,
      histFloatOffset + 4 * 256,
    );

    // Free the histogram buffer returned by WASM.
    m._free(histPtr);

    // Split into separate channels (each 256 float32s)
    const rgb = histogramFloat32.subarray(0, 256);
    const red = histogramFloat32.subarray(256, 512);
    const green = histogramFloat32.subarray(512, 768);
    const blue = histogramFloat32.subarray(768, 1024);

    return { rgb, red, green, blue };
  } finally {
    m._free(pixPtr);
    if (maskPtr) {
      m._free(maskPtr);
    }
  }
}

/**
 * Affine transform via inverse-mapping.
 * invMatrix: [a, b, tx, c, d, ty] — maps output (x,y) to source (u,v):
 *   u = a*x + b*y + tx
 *   v = c*x + d*y + ty
 * interp: 0=nearest, 1=bilinear, 2=bicubic
 */
export async function applyAffineTransform(
  src: Uint8Array,
  srcW: number,
  srcH: number,
  dstW: number,
  dstH: number,
  invMatrix: Float32Array,
  interp: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const matPtr = m._malloc(invMatrix.byteLength);
  try {
    m.HEAPF32.set(invMatrix, matPtr / 4);
    return withSrcDstBuffers(m, src, dstW * dstH * 4, (srcPtr, dstPtr) =>
      m._pixelops_affine_transform(
        srcPtr,
        srcW,
        srcH,
        dstPtr,
        dstW,
        dstH,
        matPtr,
        interp,
      ),
    );
  } finally {
    m._free(matPtr);
  }
}

/**
 * Perspective transform via inverse 3×3 homography.
 * invH: 9 elements, row-major — maps output (x,y) to source (u,v) via:
 *   [u, v, w] = invH * [x, y, 1]ᵀ;  srcX = u/w, srcY = v/w
 * interp: 0=nearest, 1=bilinear, 2=bicubic
 */
export async function applyPerspectiveTransform(
  src: Uint8Array,
  srcW: number,
  srcH: number,
  dstW: number,
  dstH: number,
  invH: Float32Array,
  interp: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const matPtr = m._malloc(invH.byteLength);
  try {
    m.HEAPF32.set(invH, matPtr / 4);
    return withSrcDstBuffers(m, src, dstW * dstH * 4, (srcPtr, dstPtr) =>
      m._pixelops_perspective_transform(
        srcPtr,
        srcW,
        srcH,
        dstPtr,
        dstW,
        dstH,
        matPtr,
        interp,
      ),
    );
  } finally {
    m._free(matPtr);
  }
}

/**
 * Rotate an RGBA image (4 bytes/pixel).
 * amount: 0 = 90°CW, 1 = 180°, 2 = 270°CW
 * Returns a new Uint8Array with dimensions swapped for 90/270, same for 180.
 */
export async function rotateRgba(
  src: Uint8Array,
  srcW: number,
  srcH: number,
  amount: 0 | 1 | 2,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const dstW = amount === 1 ? srcW : srcH;
  const dstH = amount === 1 ? srcH : srcW;
  return withSrcDstBuffers(m, src, dstW * dstH * 4, (srcPtr, dstPtr) =>
    m._pixelops_rotate_rgba(srcPtr, srcW, srcH, dstPtr, amount),
  );
}

/**
 * Flip an RGBA image (4 bytes/pixel).
 * axis: 0 = horizontal, 1 = vertical
 */
export async function flipRgba(
  src: Uint8Array,
  w: number,
  h: number,
  axis: 0 | 1,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withSrcDstBuffers(m, src, w * h * 4, (srcPtr, dstPtr) =>
    m._pixelops_flip_rgba(srcPtr, w, h, dstPtr, axis),
  );
}

/**
 * Rotate an indexed (1 byte/pixel) image.
 * amount: 0 = 90°CW, 1 = 180°, 2 = 270°CW
 */
export async function rotateIndexed(
  src: Uint8Array,
  srcW: number,
  srcH: number,
  amount: 0 | 1 | 2,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const dstLen = srcW * srcH; // same pixel count regardless of rotation
  return withSrcDstBuffers(m, src, dstLen, (srcPtr, dstPtr) =>
    m._pixelops_rotate_indexed(srcPtr, srcW, srcH, dstPtr, amount),
  );
}

/**
 * Flip an indexed (1 byte/pixel) image.
 * axis: 0 = horizontal, 1 = vertical
 */
export async function flipIndexed(
  src: Uint8Array,
  w: number,
  h: number,
  axis: 0 | 1,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  return withSrcDstBuffers(m, src, w * h, (srcPtr, dstPtr) =>
    m._pixelops_flip_indexed(srcPtr, w, h, dstPtr, axis),
  );
}

/**
 * Content-aware inpainting (PatchMatch).
 *
 * @param pixels   RGBA flat canvas composite, width × height × 4 bytes.
 * @param width    Canvas width in pixels.
 * @param height   Canvas height in pixels.
 * @param mask     Single-channel fill mask from activeScope().selection.mask,
 *                 width × height bytes (255 = fill region, 0 = source region).
 * @param sourceMask  Optional source-eligibility mask (1 = eligible, 0 = excluded).
 *                    Pass undefined for unconstrained (sample entire image).
 * @returns        RGBA output buffer, same dimensions as pixels.
 *                 Pixels outside the mask are unchanged copies of the input.
 */
export async function inpaintRegion(
  pixels: Uint8Array,
  width: number,
  height: number,
  mask: Uint8Array,
  sourceMask?: Uint8Array,
): Promise<Uint8Array> {
  assertBytes("inpaintRegion", pixels);

  // Run on a crop around the fill instead of the whole canvas. Level 0 of
  // the PatchMatch pyramid copies every pixel plus ~20 bytes/pixel of
  // bookkeeping, so filling a small area of an 8K document used to grow the
  // WASM heap by >1.3 GB (and the heap never shrinks).
  //  - With a source mask, patches can only come from it, so cropping to
  //    fill ∪ source gives exactly the same result.
  //  - Without one, keep a generous margin of surrounding context.
  const fill = maskBounds(mask, width, height);
  if (!fill) return pixels.slice();
  let crop: MaskBounds;
  if (sourceMask !== undefined) {
    const src = maskBounds(sourceMask, width, height);
    crop = src ? unionBounds(fill, src) : fill;
  } else {
    const margin = Math.max(256, 2 * Math.max(fill.x1 - fill.x0, fill.y1 - fill.y0));
    crop = {
      x0: Math.max(0, fill.x0 - margin),
      y0: Math.max(0, fill.y0 - margin),
      x1: Math.min(width, fill.x1 + margin),
      y1: Math.min(height, fill.y1 + margin),
    };
  }
  if (crop.x0 > 0 || crop.y0 > 0 || crop.x1 < width || crop.y1 < height) {
    const cw = crop.x1 - crop.x0;
    const ch = crop.y1 - crop.y0;
    const cropped = await inpaintRegion(
      cropRegion(pixels, width, crop, 4),
      cw,
      ch,
      cropRegion(mask, width, crop, 1),
      sourceMask !== undefined ? cropRegion(sourceMask, width, crop, 1) : undefined,
    );
    const out = pixels.slice();
    for (let y = 0; y < ch; y++) {
      out.set(
        cropped.subarray(y * cw * 4, (y + 1) * cw * 4),
        ((crop.y0 + y) * width + crop.x0) * 4,
      );
    }
    return out;
  }

  const m = await getPixelOps();
  const PATCH_SIZE = 4; // → 9×9 patches
  const byteLen = pixels.byteLength; // width * height * 4

  const pixelsPtr = m._malloc(byteLen);
  const maskPtr = m._malloc(mask.byteLength);
  const outPtr = m._malloc(byteLen);
  let sourceMaskPtr = 0;
  try {
    m.HEAPU8.set(pixels, pixelsPtr);
    m.HEAPU8.set(mask, maskPtr);
    if (sourceMask !== undefined) {
      sourceMaskPtr = m._malloc(sourceMask.byteLength);
      m.HEAPU8.set(sourceMask, sourceMaskPtr);
    }
    m._pixelops_inpaint(
      pixelsPtr,
      width,
      height,
      maskPtr,
      PATCH_SIZE,
      sourceMaskPtr,
      outPtr,
    );
    // Re-read HEAPU8 in case WASM memory grew during the call
    return m.HEAPU8.slice(outPtr, outPtr + byteLen);
  } finally {
    m._free(pixelsPtr);
    m._free(maskPtr);
    if (sourceMaskPtr !== 0) m._free(sourceMaskPtr);
    m._free(outPtr);
  }
}

interface MaskBounds {
  x0: number;
  y0: number;
  x1: number;
  y1: number;
}

/** Bounding box (exclusive right/bottom) of the non-zero pixels of a
 *  1-byte-per-pixel mask, or null when it is empty. */
function maskBounds(mask: Uint8Array, w: number, h: number): MaskBounds | null {
  let x0 = w;
  let y0 = h;
  let x1 = -1;
  let y1 = -1;
  for (let y = 0; y < h; y++) {
    const row = y * w;
    for (let x = 0; x < w; x++) {
      if (mask[row + x] === 0) continue;
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
  return x1 < 0 ? null : { x0, y0, x1: x1 + 1, y1: y1 + 1 };
}

function unionBounds(a: MaskBounds, b: MaskBounds): MaskBounds {
  return {
    x0: Math.min(a.x0, b.x0),
    y0: Math.min(a.y0, b.y0),
    x1: Math.max(a.x1, b.x1),
    y1: Math.max(a.y1, b.y1),
  };
}

/** Copy a rectangle out of a row-major buffer with `bpp` bytes per pixel. */
function cropRegion(
  src: Uint8Array,
  srcW: number,
  r: MaskBounds,
  bpp: number,
): Uint8Array {
  const cw = r.x1 - r.x0;
  const out = new Uint8Array(cw * (r.y1 - r.y0) * bpp);
  for (let y = r.y0; y < r.y1; y++) {
    const from = (y * srcW + r.x0) * bpp;
    out.set(src.subarray(from, from + cw * bpp), (y - r.y0) * cw * bpp);
  }
  return out;
}

/**
 * GrabCut segmentation (Rother et al. 2004).
 *
 * @param pixels    RGBA image, width×height×4 bytes.
 * @param width     Image width.
 * @param height    Image height.
 * @param trimap    Per-pixel trimap: 0=BG, 128=unknown, 255=FG. width×height bytes.
 * @param iterations EM iterations (3 is typically sufficient).
 * @param k         GMM components per class (5 recommended).
 * @returns         Binary alpha mask (0 or 255), width×height bytes.
 */
export async function grabCut(
  pixels: Uint8Array,
  width: number,
  height: number,
  trimap: Uint8Array,
  iterations = 3,
  k = 5,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const n = width * height;

  const rgbaPtr = m._malloc(pixels.byteLength);
  const trimapPtr = m._malloc(n);
  const alphaPtr = m._malloc(n);
  try {
    m.HEAPU8.set(pixels, rgbaPtr);
    m.HEAPU8.set(trimap, trimapPtr);
    m._pixelops_grabcut(
      rgbaPtr,
      width,
      height,
      trimapPtr,
      alphaPtr,
      iterations,
      k,
    );
    // Re-read HEAPU8 in case WASM memory grew
    return m.HEAPU8.slice(alphaPtr, alphaPtr + n);
  } finally {
    m._free(rgbaPtr);
    m._free(trimapPtr);
    m._free(alphaPtr);
  }
}

// ─── GrabCut hybrid building blocks ──────────────────────────────────────────

/** Compute beta (1/2 contrast) for the image. */
export async function grabCutComputeBeta(
  pixels: Uint8Array,
  width: number,
  height: number,
): Promise<number> {
  const m = await getPixelOps();
  const rgbaPtr = m._malloc(pixels.byteLength);
  try {
    m.HEAPU8.set(pixels, rgbaPtr);
    return m._pixelops_grabcut_compute_beta(rgbaPtr, width, height);
  } finally {
    m._free(rgbaPtr);
  }
}

/** Initialise both GMMs from the trimap via k-means++.
 *  Returns a Float32Array of length 2*k*20 (FG first, then BG). */
export async function grabCutKmeansInit(
  pixels: Uint8Array,
  width: number,
  height: number,
  trimap: Uint8Array,
  k: number,
): Promise<Float32Array> {
  const m = await getPixelOps();
  const paramsLen = 2 * k * 20;
  const paramsBytes = paramsLen * 4;
  const rgbaPtr = m._malloc(pixels.byteLength);
  const trimapPtr = m._malloc(trimap.byteLength);
  const paramsPtr = m._malloc(paramsBytes);
  try {
    m.HEAPU8.set(pixels, rgbaPtr);
    m.HEAPU8.set(trimap, trimapPtr);
    m._pixelops_grabcut_kmeans_init(
      rgbaPtr,
      width,
      height,
      trimapPtr,
      k,
      paramsPtr,
    );
    const off = paramsPtr / 4;
    return m.HEAPF32.slice(off, off + paramsLen);
  } finally {
    m._free(rgbaPtr);
    m._free(trimapPtr);
    m._free(paramsPtr);
  }
}

/** Re-estimate both GMMs given a binary label. Returns updated params. */
export async function grabCutUpdateGmms(
  pixels: Uint8Array,
  width: number,
  height: number,
  label: Uint8Array,
  k: number,
  params: Float32Array,
): Promise<Float32Array> {
  const m = await getPixelOps();
  const paramsLen = 2 * k * 20;
  const rgbaPtr = m._malloc(pixels.byteLength);
  const labelPtr = m._malloc(label.byteLength);
  const paramsPtr = m._malloc(params.byteLength);
  try {
    m.HEAPU8.set(pixels, rgbaPtr);
    m.HEAPU8.set(label, labelPtr);
    m.HEAPF32.set(params, paramsPtr / 4);
    m._pixelops_grabcut_update_gmms(
      rgbaPtr,
      width,
      height,
      labelPtr,
      k,
      paramsPtr,
    );
    const off = paramsPtr / 4;
    return m.HEAPF32.slice(off, off + paramsLen);
  } finally {
    m._free(rgbaPtr);
    m._free(labelPtr);
    m._free(paramsPtr);
  }
}

/** Run min-cut with externally-computed t-link and n-link arrays.
 *  Returns binary label (0 or 1) per pixel, width*height bytes. */
export async function grabCutMincut(
  capS: Float32Array,
  capT: Float32Array,
  hW: Float32Array,
  vW: Float32Array,
  trimap: Uint8Array,
  width: number,
  height: number,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const n = width * height;
  const capSPtr = m._malloc(capS.byteLength);
  const capTPtr = m._malloc(capT.byteLength);
  const hWPtr = m._malloc(hW.byteLength);
  const vWPtr = m._malloc(vW.byteLength);
  const trimapPtr = m._malloc(trimap.byteLength);
  const labelPtr = m._malloc(n);
  try {
    m.HEAPF32.set(capS, capSPtr / 4);
    m.HEAPF32.set(capT, capTPtr / 4);
    m.HEAPF32.set(hW, hWPtr / 4);
    m.HEAPF32.set(vW, vWPtr / 4);
    m.HEAPU8.set(trimap, trimapPtr);
    m._pixelops_grabcut_mincut(
      capSPtr,
      capTPtr,
      hWPtr,
      vWPtr,
      trimapPtr,
      width,
      height,
      labelPtr,
    );
    return m.HEAPU8.slice(labelPtr, labelPtr + n);
  } finally {
    m._free(capSPtr);
    m._free(capTPtr);
    m._free(hWPtr);
    m._free(vWPtr);
    m._free(trimapPtr);
    m._free(labelPtr);
  }
}

/** Maps each RGBA8 pixel to the nearest palette index (squared Euclidean distance in RGBA space).
 *  Transparent pixels (alpha == 0) are assigned transparentIdx.
 *  Returns a Uint8Array of length pixelCount containing one palette index per pixel. */
export async function matchPaletteIndices(
  rgba: Uint8Array,
  palette: Array<{ r: number; g: number; b: number; a: number }>,
  transparentIdx = 255,
): Promise<Uint8Array> {
  assertBytes("matchPaletteIndices", rgba);
  const palFlat = new Uint8Array(palette.length * 4);
  palette.forEach((c, i) => {
    palFlat[i * 4] = c.r;
    palFlat[i * 4 + 1] = c.g;
    palFlat[i * 4 + 2] = c.b;
    palFlat[i * 4 + 3] = c.a;
  });

  const m = await getPixelOps();
  const pixelCount = rgba.length / 4;

  const rgbaPtr = m._malloc(rgba.byteLength);
  const palPtr = m._malloc(Math.max(palFlat.byteLength, 1));
  const outPtr = m._malloc(pixelCount);
  try {
    m.HEAPU8.set(rgba, rgbaPtr);
    if (palFlat.byteLength > 0) m.HEAPU8.set(palFlat, palPtr);
    m._matchPaletteIndices(
      rgbaPtr,
      pixelCount,
      palPtr,
      palette.length,
      outPtr,
      transparentIdx,
    );
    // Re-read HEAPU8 in case WASM memory grew during the call
    return m.HEAPU8.slice(outPtr, outPtr + pixelCount);
  } finally {
    m._free(rgbaPtr);
    m._free(palPtr);
    m._free(outPtr);
  }
}

// ─── EXR I/O ─────────────────────────────────────────────────────────────────

/**
 * Read a pointer field from a C++ result struct. The module is built with
 * MEMORY64, so pointers are 8 bytes; the C++ side stores them as uint64_t.
 * Heap is capped at 16 GB, well inside Number's safe-integer range.
 */
function readPtr(view: DataView, offset: number): number {
  return Number(view.getBigUint64(offset, true));
}

/**
 * Guard for wrappers that take 8-bit RGBA. rgba32f composites come back as
 * Float32Array, and `HEAPU8.set(Float32Array)` silently truncates every
 * value to 0 or 1 instead of failing — convert with `clampF32ToUint8` first.
 */
function assertBytes(fn: string, data: unknown): void {
  if (!(data instanceof Uint8Array) && !(data instanceof Uint8ClampedArray)) {
    throw new TypeError(
      `${fn}: expected 8-bit RGBA (Uint8Array), got ${
        (data as object)?.constructor?.name ?? typeof data
      }`,
    );
  }
}

/** Decode an OpenEXR file. */
export async function decodeExr(
  bytes: Uint8Array,
): Promise<{ pixels: Float32Array; width: number; height: number }> {
  const m = await getPixelOps();
  const srcPtr = m._malloc(bytes.byteLength);
  try {
    m.HEAPU8.set(bytes, srcPtr);
    const resultPtr = m._loadExr(srcPtr, bytes.byteLength);
    if (resultPtr === 0) throw new Error("EXR decode failed");
    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    // ExrResult { int32 width; int32 height; uint64 pixels; }
    const width = view.getInt32(resultPtr, true);
    const height = view.getInt32(resultPtr + 4, true);
    const pxPtr = readPtr(view, resultPtr + 8);
    const count = width * height * 4;
    const pixels = new Float32Array(count);
    const heap = new Float32Array(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    pixels.set(heap.subarray(pxPtr / 4, pxPtr / 4 + count));
    m._freeExrResult(resultPtr);
    return { pixels, width, height };
  } finally {
    m._free(srcPtr);
  }
}

/** Encode RGBA float32 pixels to OpenEXR. compression: 0=none,1=zip,2=zips,3=piz; halfFloat: 0 or 1. */
export async function encodeExr(
  pixels: Float32Array,
  width: number,
  height: number,
  compression = 0,
  halfFloat = 0,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const srcPtr = m._malloc(pixels.byteLength);
  try {
    new Float32Array(
      m.HEAPU8.buffer,
      m.HEAPU8.byteOffset + srcPtr,
      pixels.length,
    ).set(pixels);
    const resultPtr = m._saveExr(srcPtr, width, height, compression, halfFloat);
    if (resultPtr === 0) throw new Error("EXR encode failed");
    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    // ExrBytes { uint64 data; int32 size; int32 _pad; }
    const bytesPtr = readPtr(view, resultPtr);
    const outLen = view.getInt32(resultPtr + 8, true);
    const out = new Uint8Array(outLen);
    out.set(m.HEAPU8.subarray(bytesPtr, bytesPtr + outLen));
    m._freeExrBytes(resultPtr);
    return out;
  } finally {
    m._free(srcPtr);
  }
}

export interface ExrDecodedLayer {
  name: string;
  width: number;
  height: number;
  offsetX: number;
  offsetY: number;
  pixels: Float32Array;
}

export interface ExrMultiDecodeResult {
  canvasWidth: number;
  canvasHeight: number;
  layers: ExrDecodedLayer[];
}

/** Read a null-terminated UTF-8 string from the WASM heap. */
function readCString(heap: Uint8Array, ptr: number): string {
  let end = ptr;
  while (end < heap.length && heap[end] !== 0) end++;
  return new TextDecoder("utf-8").decode(heap.subarray(ptr, end));
}

/** Decode an EXR file into one or more named layers. */
export async function decodeExrLayers(
  bytes: Uint8Array,
): Promise<ExrMultiDecodeResult> {
  const m = await getPixelOps();
  const srcPtr = m._malloc(bytes.byteLength);
  let resultPtr = 0;
  try {
    m.HEAPU8.set(bytes, srcPtr);
    resultPtr = m._loadExrLayers(srcPtr, bytes.byteLength);
    if (resultPtr === 0) throw new Error("EXR multi-layer decode failed");

    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    // ExrMultiResult { int32 w; int32 h; int32 numLayers; int32 _pad; uint64 layersPtr; }
    const canvasWidth = view.getInt32(resultPtr, true);
    const canvasHeight = view.getInt32(resultPtr + 4, true);
    const numLayers = view.getInt32(resultPtr + 8, true);
    const layersPtr = readPtr(view, resultPtr + 16);

    const layers: ExrDecodedLayer[] = [];
    const STRIDE = 32; // sizeof(ExrLayerOut)
    for (let i = 0; i < numLayers; i++) {
      const base = layersPtr + i * STRIDE;
      const w = view.getInt32(base, true);
      const h = view.getInt32(base + 4, true);
      const offX = view.getInt32(base + 8, true);
      const offY = view.getInt32(base + 12, true);
      const namePtr = readPtr(view, base + 16);
      const pxPtr = readPtr(view, base + 24);
      const name = readCString(m.HEAPU8, namePtr);
      const count = w * h * 4;
      const pixels = new Float32Array(count);
      const heapF32 = new Float32Array(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
      pixels.set(heapF32.subarray(pxPtr / 4, pxPtr / 4 + count));
      layers.push({
        name,
        width: w,
        height: h,
        offsetX: offX,
        offsetY: offY,
        pixels,
      });
    }
    return { canvasWidth, canvasHeight, layers };
  } finally {
    if (resultPtr !== 0) m._freeExrLayersResult(resultPtr);
    m._free(srcPtr);
  }
}

/**
 * Encode multiple full-canvas RGBA float32 layers into a single-part EXR with
 * channel-named groups ("<LayerName>.R/G/B/A").  Each layer's `pixels` must be
 * width*height*4 floats.
 */
export async function encodeExrLayers(
  layers: ReadonlyArray<{ name: string; pixels: Float32Array }>,
  width: number,
  height: number,
  compression = 0,
  halfFloat = 0,
): Promise<Uint8Array> {
  if (layers.length === 0) throw new Error("encodeExrLayers: no layers given");
  const m = await getPixelOps();

  // Pack names: null-separated UTF-8.
  const enc = new TextEncoder();
  const nameBufs = layers.map((l) => enc.encode(l.name));
  const nameBytes = nameBufs.reduce((s, b) => s + b.length + 1, 0);
  const namesBuf = new Uint8Array(nameBytes);
  {
    let off = 0;
    for (const nb of nameBufs) {
      namesBuf.set(nb, off);
      off += nb.length;
      namesBuf[off++] = 0;
    }
  }

  // Pack pixels: layer-major contiguous.
  const pixelsPerLayer = width * height * 4;
  const totalFloats = pixelsPerLayer * layers.length;
  const namesPtr = m._malloc(namesBuf.byteLength);
  const pixelsPtr = m._malloc(totalFloats * 4);
  let resultPtr = 0;
  try {
    m.HEAPU8.set(namesBuf, namesPtr);
    const heapF32 = new Float32Array(
      m.HEAPU8.buffer,
      m.HEAPU8.byteOffset + pixelsPtr,
      totalFloats,
    );
    for (let i = 0; i < layers.length; i++) {
      if (layers[i].pixels.length !== pixelsPerLayer) {
        throw new Error(
          `encodeExrLayers: layer ${i} (${layers[i].name}) has ${layers[i].pixels.length} floats, expected ${pixelsPerLayer}`,
        );
      }
      heapF32.set(layers[i].pixels, i * pixelsPerLayer);
    }
    resultPtr = m._saveExrLayers(
      width,
      height,
      layers.length,
      namesPtr,
      pixelsPtr,
      compression,
      halfFloat,
    );
    if (resultPtr === 0) throw new Error("EXR multi-layer encode failed");
    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    // ExrBytes { uint64 data; int32 size; int32 _pad; }
    const bytesPtr = readPtr(view, resultPtr);
    const outLen = view.getInt32(resultPtr + 8, true);
    const out = new Uint8Array(outLen);
    out.set(m.HEAPU8.subarray(bytesPtr, bytesPtr + outLen));
    return out;
  } finally {
    if (resultPtr !== 0) m._freeExrBytes(resultPtr);
    m._free(namesPtr);
    m._free(pixelsPtr);
  }
}

// ─── DDS I/O ─────────────────────────────────────────────────────────────────

export const DdsFormat = {
  BC1: 1,
  BC2: 2,
  BC3: 3,
  BC4: 4,
  BC5: 5,
  BC6H: 6,
  BC7: 7,
  RGBA8: 8,
  RGBA32F: 9,
} as const;
export type DdsFormat = (typeof DdsFormat)[keyof typeof DdsFormat];

export const DdsHeaderMode = {
  AUTO: 0,
  DX9: 1,
  DX10: 2,
} as const;

export interface DdsInfo {
  width: number;
  height: number;
  fmt: DdsFormat;
  mipLevels: number;
}

function ddsErrorFromCode(code: number): string {
  switch (code) {
    case -1:
      return "DDS: invalid file";
    case -2:
      return "DDS: unsupported format";
    case -3:
      return "DDS: output buffer too small";
    default:
      return `DDS: error code ${code}`;
  }
}

/** Parse DDS header metadata. */
export async function getDdsInfo(bytes: Uint8Array): Promise<DdsInfo> {
  const m = await getPixelOps();
  const dataPtr = m._malloc(bytes.byteLength);
  const outPtr = m._malloc(16); // 4 × int32
  try {
    m.HEAPU8.set(bytes, dataPtr);
    const err = m._pixelops_dds_get_info(dataPtr, bytes.byteLength, outPtr);
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const view = new DataView(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    return {
      width: view.getInt32(outPtr, true),
      height: view.getInt32(outPtr + 4, true),
      fmt: view.getInt32(outPtr + 8, true) as DdsFormat,
      mipLevels: view.getInt32(outPtr + 12, true),
    };
  } finally {
    m._free(dataPtr);
    m._free(outPtr);
  }
}

/** Decode a DDS file to RGBA8 pixels. BC6H and RGBA32F are tonemapped to SDR. */
export async function decodeDds(
  bytes: Uint8Array,
): Promise<{ pixels: Uint8Array; width: number; height: number }> {
  const m = await getPixelOps();
  const info = await getDdsInfo(bytes);
  const { width, height } = info;
  const outSize = width * height * 4;
  const dataPtr = m._malloc(bytes.byteLength);
  const outPtr = m._malloc(outSize);
  try {
    m.HEAPU8.set(bytes, dataPtr);
    const err = m._pixelops_dds_decode(
      dataPtr,
      bytes.byteLength,
      outPtr,
      outSize,
    );
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const pixels = new Uint8Array(outSize);
    pixels.set(m.HEAPU8.subarray(outPtr, outPtr + outSize));
    return { pixels, width, height };
  } finally {
    m._free(dataPtr);
    m._free(outPtr);
  }
}

/** Decode a DDS file to RGBA float32 pixels. */
export async function decodeDdsF32(
  bytes: Uint8Array,
): Promise<{ pixels: Float32Array; width: number; height: number }> {
  const m = await getPixelOps();
  const info = await getDdsInfo(bytes);
  const { width, height } = info;
  const outSize = width * height * 16; // 4 floats × 4 bytes
  const dataPtr = m._malloc(bytes.byteLength);
  const outPtr = m._malloc(outSize);
  try {
    m.HEAPU8.set(bytes, dataPtr);
    const err = m._pixelops_dds_decode_f32(
      dataPtr,
      bytes.byteLength,
      outPtr,
      outSize,
    );
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const pixels = new Float32Array(width * height * 4);
    const heap = new Float32Array(m.HEAPU8.buffer, m.HEAPU8.byteOffset);
    pixels.set(heap.subarray(outPtr / 4, outPtr / 4 + pixels.length));
    return { pixels, width, height };
  } finally {
    m._free(dataPtr);
    m._free(outPtr);
  }
}

/** Encode RGBA8 pixels to a DDS file (BC1, BC3, BC7). */
export async function encodeDds(
  pixels: Uint8Array,
  width: number,
  height: number,
  fmt: number,
  mipLevels: number = 1,
  headerMode: number = DdsHeaderMode.AUTO,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const outSize = m._pixelops_dds_get_encoded_size(
    width,
    height,
    fmt,
    mipLevels,
    headerMode,
  );
  if (outSize <= 0) throw new Error(ddsErrorFromCode(outSize));
  const srcPtr = m._malloc(pixels.byteLength);
  const outPtr = m._malloc(outSize);
  try {
    m.HEAPU8.set(pixels, srcPtr);
    const err = m._pixelops_dds_encode(
      srcPtr,
      width,
      height,
      fmt,
      mipLevels,
      headerMode,
      outPtr,
      outSize,
    );
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const out = new Uint8Array(outSize);
    out.set(m.HEAPU8.subarray(outPtr, outPtr + outSize));
    return out;
  } finally {
    m._free(srcPtr);
    m._free(outPtr);
  }
}

/** Encode RGBA float32 pixels to a DDS file (BC6H UF16 or raw RGBA32F). */
export async function encodeDdsF32(
  pixels: Float32Array,
  width: number,
  height: number,
  fmt: number,
  mipLevels: number = 1,
): Promise<Uint8Array> {
  const m = await getPixelOps();
  const outSize = m._pixelops_dds_get_encoded_size(
    width,
    height,
    fmt,
    mipLevels,
    DdsHeaderMode.DX10,
  );
  if (outSize <= 0) throw new Error(ddsErrorFromCode(outSize));
  const srcPtr = m._malloc(pixels.byteLength);
  const outPtr = m._malloc(outSize);
  try {
    new Float32Array(
      m.HEAPU8.buffer,
      m.HEAPU8.byteOffset + srcPtr,
      pixels.length,
    ).set(pixels);
    const err = m._pixelops_dds_encode_f32(
      srcPtr,
      width,
      height,
      fmt,
      mipLevels,
      DdsHeaderMode.DX10,
      outPtr,
      outSize,
    );
    if (err !== 0) throw new Error(ddsErrorFromCode(err));
    const out = new Uint8Array(outSize);
    // Re-read HEAPU8 in case WASM memory grew
    out.set(m.HEAPU8.subarray(outPtr, outPtr + outSize));
    return out;
  } finally {
    m._free(srcPtr);
    m._free(outPtr);
  }
}

/** Maximum mip levels such that the smallest dimension is >= minDim. */
export async function maxDdsMipLevels(
  width: number,
  height: number,
  minDim: number,
): Promise<number> {
  const m = await getPixelOps();
  return m._pixelops_dds_max_mip_levels(width, height, minDim);
}

// ─── Brush stamp inner loop ──────────────────────────────────────────────────
export {
  runBrushStamp,
  beginBrushBatch,
  beginBrushBatchBitmap,
  appendBrushStamp,
  flushBrushBatch,
  ensureBakedBitmap,
  type BrushStampJob,
  type BrushBakeShape,
  type BakedBitmap,
} from "./brushStamp";

// ─── WASM-heap-resident typed-array storage ─────────────────────────────────
export {
  allocWasmU8,
  allocWasmF32,
  freeWasm,
  syncIfGrew,
} from "./wasmHeapStorage";
